language: python
sudo: false

branches:
  only:
    - master
    - next

matrix:
  fast_finish: true
  include:
    - python: "pypy3"
      env: JCMSPROFILE=yes
    - python: "nightly"
      env: JCMSPROFILE=yes
    - python: "3.5"
    - python: "3.6"

install:
  - pip install -q -r requirements.txt
  - cython --version
  - cc --version

before_script:
  - make buildext
  - make build
  - make clean
  - python3 -m jcms.version_t

script:
  - make coverage
  - if test 'Xyes' = "X$JCMSPROFILE"; then make profile; fi

after_success:
  - make distclean dist
  - python3 -m jcms.version
