language: python
sudo: false

branches:
  only:
    - master
    - next

matrix:
  fast_finish: true

python:
  - "pypy3"
  - "nightly"
  - "3.5"
  - "3.6"

install:
  - pip install -q -r requirements.txt
  - pip install -q -r requirements-test.txt

script:
  - python3 -m version_t
  - make coverage
