language: python
sudo: false

branches:
  only:
    - master
    - next

matrix:
  fast_finish: true
  include:
    - python: "pypy3"
      env: JCMSPROFILE=yes
    - python: "nightly"
      env: JCMSPROFILE=yes
    - python: "3.5"
    - python: "3.6"

install:
  - pip install -q -r requirements.txt
  - pip install -q -r requirements-dev.txt
  - pip install -q -r requirements-test.txt

script:
  - python3 -m jcms.version_t
  - make coverage
  - if test 'Xyes' = "X$JCMSPROFILE"; then make profile; fi

after_success:
  - make dist
