language: python
sudo: false

branches:
  only:
    - master
    - next

matrix:
  fast_finish: true
  include:
    - python: "pypy3"
      env: JCMSPROFILE=yes
    - python: "nightly"
    - python: "3.5"
    - python: "3.6"

install:
  - pip install -q -r requirements.txt
  - pip install -q -r requirements-test.txt

script:
  - python3 -m version_t
  - make coverage
  - (test 'Xyes' = "X$JCMSPROFILE" && make profile) || true
