# https://www.appveyor.com/docs/appveyor-yml/
# https://ci.appveyor.com/project/jrmsgit/jcms

version: "build{build}"

branches:
  only:
    - master
    - next

image: "Visual Studio 2017"

environment:
  matrix:
    - PYTHON: "C:\\Python35"
      JCMSPROFILE: "yes"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
      JCMSPROFILE: "yes"

matrix:
  fast_finish: true

install:
  - "%PYTHON%\\python.exe -m pip install -q -r requirements.txt"

build: off

before_test:
  - "%PYTHON%\\python.exe --version"
  - "%PYTHON%\\python.exe -m cython --version"
  - "%PYTHON%\\python.exe setup.py build_ext"
  - "%PYTHON%\\python.exe setup.py build"
  - "%PYTHON%\\python.exe setup.py clean -va"
  - "git clean -xfd"

test_script:
  - "%PYTHON%\\python.exe -m coverage run jcmstest.py"
  - "%PYTHON%\\python.exe -m coverage report"
  - "IF Xyes==X%JCMSPROFILE% %PYTHON%\\python.exe jcmsprof.py"

after_test:
  - "%PYTHON%\\python.exe setup.py clean -va"
  - "git clean -xfd"
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - "%PYTHON%\\python.exe -m jcms.version"

artifacts:
  - path: dist\*
